### ISSUE TITLE
🐰 Bunny Day DIY Recipe progress

### ISSUE THREAD

**Issue by skullface** [skullface/acnh#15]
## Furniture
* [x] Bunny Day bed
* [x] Bunny Day wall clock
* [x] Bunny Day glowy garland
* [x] Bunny Day lamp
* [x] Bunny Day stool
* [x] Bunny Day vanity
* [x] Bunny Day table
* [x] Bunny Day wreath
* [x] Bunny Day crown
* [x] Bunny Day bag
* [x] Bunny Day fence
* [x] Bunny Day wall
* [x] Bunny Day flooring
* [x] Bunny Day rug
* [x] Bunny Day merry balloons
* [x] Bunny Day festive balloons
* [x] Bunny Day wardrobe

## Clothing
* [x] Bunny Day outfit
  * [x] Earth-egg
  * [x] Stone-egg
  * [x] Leaf-egg
  * [x] Wood-egg
  * [x] Sky-egg
  * [x] Water-egg
* [x] Bunny Day shell (hat)
  * [x] Earth-egg
  * [x] Stone-egg
  * [x] Leaf-egg
  * [x] Wood-egg
  * [x] Sky-egg
  * [x] Water-egg
* [x] Bunny Day shoes
  * [x] Earth-egg
  * [x] Stone-egg
  * [x] Leaf-egg
  * [x] Wood-egg
  * [x] Sky-egg
  * [x] Water-egg
* [x] Egg party dress

## April 12th recipes
After crafting all of the furniture, you’ll receive the recipes for the following from Zipper:
* [x] Bunny Day arch
* [x] Bunny Day Zipper toy
* [x] Bunny Day wand
