### ISSUE TITLE
🎋 Bamboo DIY Recipes progress

### ISSUE THREAD

**Issue by skullface** [skullface/acnh#16]
* [x] **Bamboo-grove wall**
  * [ ] 7 young spring bamboo
  * [x] 3 bamboo shoots
* [x] **Light bamboo rug**
  * [x] 6 young spring bamboo
* [x] **Bamboo wand**
  * [x] 6 young spring bamboo
  * [x] 3 star fragment
* [x] **Basket pack**
  * [x] 6 young spring bamboo
* [x] **Green-leaf pile**
  * [x] 1 young spring bamboo
  * [x] 10 clump of weeds
* [x] **Steamer-basket set**
  * [x] 6 young spring bamboo
* [x] **Bamboo-shoot lamp**
  * [x] 4 young spring bamboo
  * [x] 5 bamboo shoots
  * [x] 4 clay
* [x] **Bamboo noodle slide**
  * [x] 7 young spring bamboo
  * [x] 3 wood
* [x] **Pan flute**
  * [x] 7 young spring bamboo
* [x] **Bamboo doll**
  * [x] 6 young spring bamboo

**Comment by skullface** [comment]
Completed!
