### ISSUE TITLE
🦉 Celeste DIY Recipes progress

### ISSUE THREAD

**Issue by skullface** [skullface/acnh#27]
## Star and moon furniture
* [ ] Crescent-moon chair
* [ ] Nova light
* [ ] Star clock
* [ ] Starry garland

## Space exploration furniture
* [ ] Asteroid
* [ ] Astronaut suit
* [ ] Crewed spaceship
* [x] Flying saucer
* [x] Lunar lander
* [ ] Lunar rover
* [x] Moon
* [x] Rocket
* [x] Satellite
* [x] Space shuttle

## Clothing
* [ ] Star head
* [x] Star pochette

## Flooring + walls
* [x] Galaxy flooring
* [x] Lunar surface
* [x] Sci-fi flooring
* [x] Sci-fi wall
* [x] Starry-sky wall
* [x] Starry wall

## Wands
* [x] Star wand (very first Celeste recipe)
* [x] Golden wand
* [ ] Tree-branch wand
* [x] Wand
* [x] Iron wand
* [x] Cosmos wand
* [ ] Hyacinth wand
* [x] Lily wand
* [ ] Mums wand
* [x] Pansy wand
* [ ] Rose wand
* [x] Tulip wand
* [x] Windflower wand

## Zodiac
* [x] Aries rocking chair
* [x] Taurus bathtub
* [x] Gemini closet
* [ ] Cancer table
* [ ] Leo sculpture
* [ ] Virgo harp
* [ ] Scorpio lamp
* [ ] Sagittarius arrow
* [ ] Libra scale
* [ ] Capricorn ornament
* [ ] Aquarius urn
* [ ] Pisces lamp
